"""categoryed5

Revision ID: 019d3cba7521
Revises: b505c761d4ac
Create Date: 2024-07-11 13:47:10.032243

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '019d3cba7521'
down_revision = 'b505c761d4ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###