"""uniq

Revision ID: 02519481b26d
Revises: cc6216d62e76
Create Date: 2024-07-18 13:33:59.677762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '02519481b26d'
down_revision = 'cc6216d62e76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_manga_chapter', 'chapter', ['manga_id', 'chapter_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_manga_chapter', 'chapter', type_='unique')
    # ### end Alembic commands ###