"""cat103

Revision ID: 02fc59e55a2e
Revises: c861b479f6f1
Create Date: 2024-07-12 18:41:27.354802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '02fc59e55a2e'
down_revision = 'c861b479f6f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###