"""cat135

Revision ID: 09585049ce35
Revises: 3e03d90b23a4
Create Date: 2024-07-12 22:26:51.767434

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '09585049ce35'
down_revision = '3e03d90b23a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###