"""categoryed3

Revision ID: 0b7b7093d447
Revises: 6ce5e2da60be
Create Date: 2024-07-10 15:33:48.734552

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '0b7b7093d447'
down_revision = '6ce5e2da60be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###