"""cat132

Revision ID: 0e175d29be7b
Revises: 8ee30d185cca
Create Date: 2024-07-12 21:28:12.573835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '0e175d29be7b'
down_revision = '8ee30d185cca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###