"""cat14{

Revision ID: 167412dba061
Revises: e9084ead1ada
Create Date: 2024-07-13 11:07:30.463829

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '167412dba061'
down_revision = 'e9084ead1ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###