"""categoryed13

Revision ID: 29c6de5aa450
Revises: 83f79a4d7aff
Create Date: 2024-07-11 16:34:07.572381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '29c6de5aa450'
down_revision = '83f79a4d7aff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###