"""nur2

Revision ID: 3c4ec3118a17
Revises: a8ee9fb3aa31
Create Date: 2024-07-14 13:52:04.400722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '3c4ec3118a17'
down_revision = 'a8ee9fb3aa31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###