"""cat134

Revision ID: 3e03d90b23a4
Revises: 9716f86e8755
Create Date: 2024-07-12 22:25:34.924380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '3e03d90b23a4'
down_revision = '9716f86e8755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###