"""categoryed15

Revision ID: 4b86004290a9
Revises: 29c6de5aa450
Create Date: 2024-07-11 16:35:13.279187

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '4b86004290a9'
down_revision = '29c6de5aa450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###