"""cat137

Revision ID: 66f564f111a4
Revises: caabba1eff8c
Create Date: 2024-07-12 22:33:10.364656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '66f564f111a4'
down_revision = 'caabba1eff8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###