"""categoryed

Revision ID: 6ce5e2da60be
Revises: 6fbb75e8186f
Create Date: 2024-07-10 15:26:34.418279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '6ce5e2da60be'
down_revision = '6fbb75e8186f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###