"""categoryed

Revision ID: 6fbb75e8186f
Revises: 3a664a99e5d2
Create Date: 2024-07-10 15:24:40.979507

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '6fbb75e8186f'
down_revision = '3a664a99e5d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###