"""cat100

Revision ID: 709b9631e8cc
Revises: 3d53069c7608
Create Date: 2024-07-12 18:08:50.901372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '709b9631e8cc'
down_revision = '3d53069c7608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('read_count', sa.Integer(), server_default='0',nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'read_count')
    # ### end Alembic commands ###