"""categoryed13

Revision ID: 83f79a4d7aff
Revises: cc68a22f32d5
Create Date: 2024-07-11 16:27:08.430185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '83f79a4d7aff'
down_revision = 'cc68a22f32d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###