"""cat141

Revision ID: 886858d1c817
Revises: 8bf6d28630d9
Create Date: 2024-07-13 10:32:05.270920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '886858d1c817'
down_revision = '8bf6d28630d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###