"""cat140

Revision ID: 8bf6d28630d9
Revises: a2c03a145738
Create Date: 2024-07-13 10:30:20.362245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '8bf6d28630d9'
down_revision = 'a2c03a145738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###