"""cat133

Revision ID: 9716f86e8755
Revises: 0e175d29be7b
Create Date: 2024-07-12 22:22:33.327961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '9716f86e8755'
down_revision = '0e175d29be7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###