"""slug

Revision ID: 994281017c89
Revises: 02519481b26d
Create Date: 2024-07-20 17:33:43.531720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '994281017c89'
down_revision = '02519481b26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'manga', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manga', type_='unique')
    op.drop_column('manga', 'slug')
    # ### end Alembic commands ###