"""cat139

Revision ID: a2c03a145738
Revises: f8c06c55f041
Create Date: 2024-07-13 10:28:22.653881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'a2c03a145738'
down_revision = 'f8c06c55f041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###