"""cat151

Revision ID: a8ee9fb3aa31
Revises: 167412dba061
Create Date: 2024-07-13 11:21:09.324160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'a8ee9fb3aa31'
down_revision = '167412dba061'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('manga', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('manga', sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('manga', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('manga', sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('manga', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'rating')
    op.drop_column('manga', 'year')
    op.drop_column('manga', 'publisher')
    op.drop_column('manga', 'status')
    op.drop_column('manga', 'genre')
    op.drop_column('manga', 'language')
    op.drop_column('manga', 'artist')
    # ### end Alembic commands ###