"""categoryed4

Revision ID: b505c761d4ac
Revises: 0b7b7093d447
Create Date: 2024-07-10 15:35:38.653603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'b505c761d4ac'
down_revision = '0b7b7093d447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###