"""cat104

Revision ID: b9299a4fea87
Revises: 02fc59e55a2e
Create Date: 2024-07-12 19:31:55.765963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'b9299a4fea87'
down_revision = '02fc59e55a2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###