"""categoryed6

Revision ID: bb3007359b96
Revises: 019d3cba7521
Create Date: 2024-07-11 13:51:08.657215

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'bb3007359b96'
down_revision = '019d3cba7521'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###