"""nur3

Revision ID: c5f7eeb2f395
Revises: 3c4ec3118a17
Create Date: 2024-07-14 14:09:11.372019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'c5f7eeb2f395'
down_revision = '3c4ec3118a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###