"""nur4

Revision ID: cc6216d62e76
Revises: c5f7eeb2f395
Create Date: 2024-07-14 20:03:40.519014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'cc6216d62e76'
down_revision = 'c5f7eeb2f395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email', 'user', ['email'])
    op.create_unique_constraint('uq_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_username', 'user', type_='unique')
    op.drop_constraint('uq_email', 'user', type_='unique')
    # ### end Alembic commands ###