"""categoryed1

Revision ID: cc68a22f32d5
Revises: bb3007359b96
Create Date: 2024-07-11 14:03:52.864813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'cc68a22f32d5'
down_revision = 'bb3007359b96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###