"""cat145

Revision ID: e9084ead1ada
Revises: 8a816fe1a258
Create Date: 2024-07-13 11:05:44.728799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'e9084ead1ada'
down_revision = '8a816fe1a258'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###