"""cat101

Revision ID: f71b26ff91ee
Revises: 709b9631e8cc
Create Date: 2024-07-12 18:10:43.209868

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'f71b26ff91ee'
down_revision = '709b9631e8cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###